### ISSUE TITLE
麻烦问一下怎么快速回到第一屏

### ISSUE THREAD

**Issue by yanxitao** [yokiyokiyoki/vue-fullpage#10]
麻烦问一下怎么快速回到第一屏

**Comment by yokiyokiyoki** [comment]
https://github.com/yokiyokiyoki/vue-fullpage/blob/master/src/App.vue#L37
this.$refs['fullpage'].move(1)

**Comment by yanxitao** [comment]
还得麻烦一下，我这回到第一屏的方法是在一个公共组件写的（直接写在APP.vue里的），但是引入fullpage的页面只是其中一个，我用document、jquery获取，都会报错。要怎么获取。麻烦您了
