### ISSUE TITLE
想问一下如果最后一页不是整屏的情况

### ISSUE THREAD

**Issue by woodenhilled** [yokiyokiyoki/vue-fullpage#11]
如题，如果最后一页不是整屏，且最后一页不想滚动整屏应该如何更改设置呢？

**Comment by yokiyokiyoki** [comment]
不是整屏的且不滚动，单独画最后一页。最后一页应该不需要用这个组件才对呀。

**Comment by woodenhilled** [comment]
需求大概是这样：
倒数第二屏是整屏，最后一屏只有200px高，从倒数第二屏往最后一屏滚动的时候只滚动最后一屏的200px，呈现的页面应该是保留部分倒数第二屏的内容。
然后最后一屏往倒数第二屏回滚结束后，依旧是倒数第二屏的整屏。
