### ISSUE TITLE
在section里绘制echart无法显示

### ISSUE THREAD

**Issue by yanxitao** [yokiyokiyoki/vue-fullpage#4]
在您这单屏的section里绘制echart无法显示，测试过普通div里是可以的，能否告知如何解决

**Comment by yokiyokiyoki** [comment]
请问你是怎么写的呢

**Comment by yanxitao** [comment]
<div id="main" style="width: auto;height:100%; margin: 0 auto;"></div>

**Comment by yanxitao** [comment]
<div slot="section">
            <div class="section main-echart">
                <p class='main-echart-title'>中国特色法律服务创新之路</p>
                <div class="echartBg">
                    <div class='mainBigechart'>
                        <div id="main" style="width: auto;height:100%; margin: 0 auto;"></div>
                    </div>
                </div>

            </div>


        var echarts = require('echarts');
        var show_id = document.getElementById('main');
        var myChart = echarts.init(show_id);

在您的slot里就无法展示

---------------------------------------------------------------------------------------------------------------------------
          <div class="section" style="height: 100vh">
            <div class="section main-echart ">
                <p class='main-echart-title'>中国特色法律服务创新之路</p>
                <div class="echartBg">
                    <div class='mainBigechart'>
                        <div id="main" style="width: auto;height:100%; margin: 0 auto;"></div>
                    </div>
                </div>

            </div>

        var echarts = require('echarts');
        var show_id = document.getElementById('main');
        var myChart = echarts.init(show_id);

同样的用法，写在没有插槽的div里就是正常的

**Comment by yokiyokiyoki** [comment]
run了一下是可以，具体栗子可以参考https://github.com/yokiyokiyoki/vue-fullpage/blob/master/src/App.vue#L5。
1.把整个仓库clone到本地
2.yarn/npm下载相关包
3.npm run serve 运行本地服务，localhost:8080即可看到两个图表切换

**Comment by yanxitao** [comment]
解决了，不是其他原因，是加载顺序的问题，定义图表时候给一个延时1秒就解决了。。
